name: bined
title: BinEd
version: '0.2.3'
summary: Binary/Hex Editor
description: |
  Free and open source hex viewer/editor written in Java.
  Features:
  - Visualize data as numerical (hexadecimal) codes and text representation
  - Codes can be also binary, octal or decimal
  - Support for Unicode, UTF-8 and other charsets
  - Insert and overwrite edit modes
  - Searching for text / hexadecimal code with matching highlighting
  - Support for undo/redo
  - Support for files with size up to exabytes
website: https://bined.exbin.org/editor
source-code: https://github.com/exbin/bined
base: core22
license: Apache-2.0
compression: lzo
icon: bined.svg

grade: stable
confinement: strict

architectures:
  - build-on: [amd64]
  - build-on: [arm64]
  - build-on: [ppc64el]

apps:
  bined:
    common-id: org.exbin.bined
    extensions: [ gnome ]
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-17-openjdk-$CRAFT_ARCH_BUILD_FOR
      HOME: "$SNAP_USER_COMMON"
      PATH: $JAVA_HOME/bin:$PATH
    command: $JAVA_HOME/bin/java -jar /app/bined-0.2.3/bined.jar
    desktop: $SNAP/app/setup/gui/bined.desktop
    plugs:
      - desktop
      - audio-playback
      - network
      - network-bind
      - home
      - x11
      - opengl
      - removable-media
      - optical-drive

parts:
  bined:
    plugin: dump
    source: https://bined.exbin.org/download/bined-0.2.3.zip
    organize:
      bined-0.2.3: /app/bined-0.2.3
    stage-packages:
      - openjdk-17-jdk
  bined-snap:
    after: [bined]
    plugin: dump
    source: https://bined.exbin.org/download/bined-snap-0.2.3.src.zip
